#!/usr/bin/python3
import sys
import os

submission_id = sys.argv[1]
full_score = float(sys.argv[2])
start_test = int(sys.argv[3])
end_test = int(sys.argv[4])

result = 0
for i in range(start_test, end_test+1):
    targ_path = os.path.join("/tmp/grader", submission_id, str(i)+".check")
    if not os.path.exists(targ_path):
        continue
    f = open(targ_path, "r")
    lines = f.read().split("\n")
    f.close()
    score = float(lines[1])
    result += score
print(result * full_score / (end_test - start_test + 1) / 100)
