#!/usr/bin/python3
import os
import subprocess
import sys

base_dir = sys.argv[1]
source_file = sys.argv[2]

capture = subprocess.run(['/usr/bin/javac', '-d', base_dir, source_file],
                         stdout=subprocess.PIPE,
                         stderr=subprocess.STDOUT)

f = open(os.path.join(base_dir, "compileMsg"), "w")
f.write(capture.stdout.decode("utf-8"))
f.close()
if not os.path.exists(os.path.join(base_dir, 'Main.class')):
    print(1)
else:
    print(capture.returncode)
print(os.path.join(base_dir, 'Main.class'))
