#!/usr/bin/python3
import os
import subprocess
import sys

base_dir = sys.argv[1]
source_file = sys.argv[2]

capture = subprocess.run('mv',
                         source_file,
                         os.path.join(base_dir, 'bin'),
                         stdout=subprocess.PIPE,
                         stderr=subprocess.STDOUT)

f = open(os.path.join(base_dir, "compileMsg"), "w")
f.write(capture.stdout)
f.close()
print(capture.returncode)
print(os.path.join(base_dir, 'bin'))
